apiVersion: apps/v1
kind: Deployment
metadata:
  name: todo-server
  namespace: dev
  labels:  
    app: todo-server
    component: backend
spec:
  replicas: 3
  selector:
    matchLabels:
      app: todo-server
  template:
    metadata:
      labels:
        app: todo-server
    spec:
      containers:
        - name: todo-server
          image: getdondev/todo-server:test
          imagePullPolicy: Always
          resources:
            requests:
              cpu: "100m"
              memory: "20Mi"
            limits:
              cpu: "500m"
              memory: "256Mi"
          ports:
            - containerPort: 8080
          startupProbe:
            httpGet:
              path: "/startup"
              port: 8080
            periodSeconds: 5
            successThreshold: 1
            failureThreshold: 10
          readinessProbe:
            httpGet:
              path: "/ready"
              port: 8080
            periodSeconds: 10
            successThreshold: 1
            failureThreshold: 2
          livenessProbe:
            httpGet:
              path: "/healthz"
              port: 8080
            periodSeconds: 10
            successThreshold: 1
            failureThreshold: 2







