apiVersion: v1
kind: Service
metadata:
  name: todo-server-svc-nodeport
spec:
  type: NodePort
  selector:
    app: todo-server
  ports:
    - nodePort: 32001
      port: 8080
      targetPort: 8080

