apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-pvc
  namespace: dev
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: mysql-local-storage
  resources:
    requests:
      storage: 50Mi
  volumeName: mysql-pv
